In [2]:
import numpy as np

In [4]:
array1 = np.arange(15,40)

In [5]:
array2 = np.arange(10,25)

In [7]:
even_array1 = np.arange(2, 20)

In [8]:
even_array2 = np.arange(34,42)

In [9]:
diff12 = np.setdiff1d(array1,array2)

In [10]:
diff12

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [13]:
matrix1 = np.stack((even_array1, even_array2), axis=0)

ValueError: all input arrays must have the same shape

In [14]:
len(even_array2)

8

In [15]:
len(even_array1)

18

In [16]:
len(array1)

25

In [17]:
len(array2)

15

In [18]:
matrix = np.arange(0,36)

In [19]:
reshape_matrix = matrix.reshape(6,6)

In [20]:
print(reshape_matrix)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [22]:
#create a 5x2 matric from standard normal distribution generated with python

nd = np.random.randn(5,2)
print(nd)

[[ 1.49252466 -1.74765398]
 [ 0.75974504  1.7286636 ]
 [ 1.6908731  -0.34546145]
 [ 0.64076245  0.38720126]
 [-1.75820119 -0.48297975]]


In [23]:
#value intersecting the last row and the last column of yout matrix
value_inter = nd[4:,1:]

In [24]:
print(nd)

[[ 1.49252466 -1.74765398]
 [ 0.75974504  1.7286636 ]
 [ 1.6908731  -0.34546145]
 [ 0.64076245  0.38720126]
 [-1.75820119 -0.48297975]]


In [25]:
print(value_inter)

[[-0.48297975]]


In [26]:
np.min(nd)

-1.7582011891572429

In [27]:
np.max(nd)

1.728663601208787

In [28]:
np.std(nd)

1.23090640352483

In [29]:
np.var(nd)

1.5151305742384316

In [30]:
np.mean(nd)

0.2365473746099523